language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

env:
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.1.*
  - SYMFONY_VERSION=3.2.*
  - SYMFONY_VERSION=3.3.*@dev

allow_failures:
  - php: hhvm

install:
  - composer install --dev

before_script:
  - cp phpunit.xml.dist phpunit.xml
  - composer require --prefer-source --dev symfony/symfony:${SYMFONY_VERSION}

script: sh -c "if [ \"$TRAVIS_PHP_VERSION\" != 'hhvm' -a \"$SYMFONY_VERSION\" = '3.2.*' ]; then ./vendor/bin/phpunit --coverage-clover=coverage.clover; else ./vendor/bin/phpunit; fi"

after_script:
  - sh -c "if [ \"$TRAVIS_PHP_VERSION\" = 'hhvm' -a \"$SYMFONY_VERSION\" = '3.2.*' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi"
  - sh -c "if [ \"$TRAVIS_PHP_VERSION\" = 'hhvm' -a \"$SYMFONY_VERSION\" = '3.2.*' ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi"

cache:
  directories:
    - $COMPOSER_CACHE_DIR
